---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: image-task
spec:
  params:
  - name: image
    description: Where to publish the resulting image.
    default: ghcr.io/bnallapeta/logo-revelio
  - name: pathToContext
    description: The path to the build context, relative to the workspace root.
    default: .
  - name: pathToDockerFile
    description: The path to the Dockerfile, relative to the workspace root.
    default: ./Dockerfile
  workspaces:
  - name: source
  - name: output
  - name: dockerconfig
    description: >-
      A workspace that consists the dockerconfigjson file.
    optional: false
  steps:
  - name: write-commit-sha
    image: alpine/git
    script: |
      cd $(workspaces.source.path)
      git rev-parse HEAD > .commit_sha
  - name: build-and-push
    image: quay.io/buildah/stable:v1.23.3
    workingDir: $(workspaces.source.path)
    script: |
      export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"
      COMMIT_SHA=$(cat $(workspaces.output.path)/.commit_sha)
      IMAGE_TAG=$(params.image):$COMMIT_SHA
      buildah bud --format=docker --tls-verify=true --no-cache \
        -f $(params.pathToDockerFile) -t $IMAGE_TAG $(params.pathToContext)
      buildah push --tls-verify=true $IMAGE_TAG docker://$IMAGE_TAG
    securityContext:
      privileged: true
