apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-build-push-task
spec:
  params:
  - name: url
    description: git url to clone
  - name: revision
    description: git revision to use
    default: "main"
  - name: image
    description: Where to publish the resulting image.
  - name: pathToContext
    description: The path to the build context, relative to the workspace root.
  - name: pathToDockerFile
    description: The path to the Dockerfile, relative to the workspace root.
  workspaces:
  - name: output
  - name: dockerconfig
  steps:
  - name: custom-git-clone
    image: alpine/git
    script: |
      git clone https://$(params.url) $(workspaces.output.path)
      cd $(workspaces.output.path)
      git fetch --all
      git checkout $(git rev-parse --short origin/$(params.revision))
  - name: skip-if-only-tekton-changed
    image: alpine/git
    workingDir: $(workspaces.output.path)
    script: |
      if [ -f .commit_sha ]; then
        LAST_COMMIT_SHA=$(cat .commit_sha)
        CURRENT_COMMIT_SHA=$(git rev-parse --short HEAD)
        git diff --quiet $LAST_COMMIT_SHA $CURRENT_COMMIT_SHA -- . ':!.tekton'
        if [ $? -eq 0 ]; then
          echo "Only changes in .tekton directory, skipping build and push."
          exit 0
        fi
      fi
  - name: update-commit-sha
    image: alpine/git
    workingDir: $(workspaces.output.path)
    script: |
      echo $(git rev-parse --short HEAD) > .commit_sha
  - name: build-and-push
    image: quay.io/buildah/stable:v1.23.3
    workingDir: $(workspaces.output.path)
    script: |
      export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"
      COMMIT_SHA=$(cat .commit_sha)
      IMAGE_TAG=$(params.image):$COMMIT_SHA
      buildah bud --format=docker --tls-verify=true --no-cache \
        -f $(params.pathToDockerFile) -t $IMAGE_TAG $(params.pathToContext)
      buildah push --tls-verify=true $IMAGE_TAG docker://$IMAGE_TAG
    securityContext:
      privileged: true
