---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-manager-role-binding
  namespace: logo-revelio
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-manager-role
  apiGroup: rbac.authorization.k8s.io
