---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: img-pipeline
spec:
  params:
  - name: image
    description: Where to publish the resulting image.
  - name: pathToContext
    description: The path to the build context, relative to the workspace root.
  - name: pathToDockerFile
    description: The path to the Dockerfile, relative to the workspace root.
  - name: gitURL
    description: git url to clone
  - name: gitRevision
    description: git revision to use
    default: "main"
  workspaces:
  - name: shared-workspace
  - name: dockerconfig
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.gitURL)
    - name: revision
      value: $(params.gitRevision)
    - name: deleteExisting
      value: "true"
  - name: build-push
    taskRef:
      name: image-task
    runAfter:
    - fetch-repo
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: dockerconfig
    params:
    - name: image
      value: $(params.image)
    - name: pathToContext
      value: $(params.pathToContext)
    - name: pathToDockerFile
      value: $(params.pathToDockerFile)
