---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: img-pipeline-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/pipeline: "[./tekton/pipelines/build-push-pipeline.yaml]"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/clone-build-push.yaml]"
spec:
  pipelineRef:
    name: clone-build-push-pipeline
  params:
  - name: image
    value: ghcr.io/bnallapeta/logo-revelio
  - name: pathToContext
    value: .
  - name: pathToDockerFile
    value: Dockerfile
  - name: gitURL
    value: https://github.com/bnallapeta/logo-revelio.git
  - name: gitRevision
    value: main
  workspaces:
  - name: shared-workspace
    emptyDir: {}
  - name: dockerconfig
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json