---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: img-pipeline-run
spec:
  pipelineRef:
    name: img-pipeline
  params:
  - name: image
    value: ghcr.io/bnallapeta/logo-revelio
  - name: pathToContext
    value: .
  - name: pathToDockerFile
    value: Dockerfile
  - name: gitURL
    value: https://github.com/bnallapeta/logo-revelio.git
  - name: gitRevision
    value: main
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
